CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE,
                        year_of_birth int NOT NULL
);

CREATE TABLE Book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name_of_book varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      publishing_year int NOT NULL,
                      taking_time timestamp,
                      person_id int REFERENCES Person(id) ON DELETE SET NULL
);
